project_id = "xylbkmcpicwyscnttosz"

[functions.send-mot-booking]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = true

[functions.save-push-subscription]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false
